### PR TITLE
thermobench: send KILL signal 3s after TERM signal

### PR DESCRIPTION
**Pull request by ametisf**
It removes the zeroing of `state.child` after a signal has been sent, but as far as I can tell the only effect that had was to prevent the signal from being sent twice in some edge cases which should not be a problem.

The thing I'm not sure about is using the `loop` variable in the `terminate_timer_cb` function because it's brought into scope through the `EV_P_` macro which may or may not introduce it depending on some defines, is it ok to use libev in this way?

### CODE REVIEW

**Comment by wentasah** [comment]
> It removes the zeroing of `state.child` after a signal has been sent, but as far as I can tell the only effect that had was to prevent the signal from being sent twice in some edge cases which should not be a problem.

Yes, this is to handle edge cases. When sending the signal for the second time, it could happen that the same PID already belongs to another process. UNIX process management is inherently racy. Linux has pidfd API to solve this, but it's quite new and not ubiquitous.

> The thing I'm not sure about is using the `loop` variable in the `terminate_timer_cb` function because it's brought into scope through the `EV_P_` macro which may or may not introduce it depending on some defines, is it ok to use libev in this way?

It would be better to register the kill timer into the loop at the beginning and only start it in the signal/timer callback.

Btw. did this change solve your problem? In my experiments, the problem is not with child process not being killed, but with grandchildren (which are not killed, because thermobench does not know about them) keeping stdout→thermobench pipe open.

**Comment by ametisf** [comment]
> Btw. did this change solve your problem?
No it didn't. I didn't notice any grandchildren but I wasn't looking for that, I'll look into it again.

**Comment by wentasah** [comment]
@ametisf Can you try the current version, whether it kill all children properly in your case?

**Comment by ametisf** [comment]
It doesn't change anything. The problem probably never was in thermobench, not even `kill -9` kills the mandelbrot benchmark during the kernel execution (shows up as D in ps) so slow benchmarks just take very long to terminate.

**Comment by ametisf** [comment]
It doesn't change anything for me. The problem probably never was in thermobench, not even `kill -9` kills the mandelbrot benchmark during the kernel execution (shows up as D in ps) so slow benchmarks just take very long time to terminate.

**Comment by wentasah** [comment]
Hmm, according to the man page, D is "_uninterruptible sleep (usually IO)_", so the process probably waits somewhere in the GPU driver, which does not allow it to be killed :-(

Do you think we can close this PR?

**Pull request closed without merging**
